allow more flexible plugin test files `test.*.py`
brain-score/core pull request #24
Opened 2023-01-29 02:22 UTC by mschrimpf

2023-01-30 02:31 UTC, kvfairchild requested changes

2023-01-30 02:31 UTC, kvfairchild commented on brainscore_core/plugin_management/test_plugins.py
> +RECOGNIZED_TEST_FILES = 'test.*.py'
```suggestion
RECOGNIZED_TEST_FILES = 'test.*\.py'
```

2023-01-30 02:31 UTC, kvfairchild commented on brainscore_core/plugin_management/test_plugins.py
> +    """Runs plugin tests (requires "test.*.py" for each plugin)
```suggestion
    """Runs plugin tests (requires "test.*\.py" for each plugin)
```

2023-01-30 02:31 UTC, kvfairchild commented on brainscore_core/plugin_management/test_plugins.py
> +        """ requires at least one file matching "test.*.py" in plugin directory, e.g. test.py, test_data.py. """
```suggestion
        """ requires at least one file matching "test.*\.py" in plugin directory, e.g. test.py, test_data.py. """
```

2023-01-30 02:31 UTC, kvfairchild commented on brainscore_core/plugin_management/test_plugins.py
> +        assert len(test_files) > 0, "No test files matching 'test.*.py' found"
```suggestion
        assert len(test_files) > 0, "No test files matching 'test.*\.py' found"
```

2023-01-30 02:31 UTC, kvfairchild commented on tests/test_plugin_management/test_test_plugins.py
> +        plugin_test_runner.validate_plugin()
```suggestion
        plugin_test_runner.validate_plugin()
        
        def test_has_testfile_valid_python(self):
        test_file = self.dummy_plugin_path / 'test.py'
        test_file.rename(self.dummy_plugin_path / 'testpluginpy')
        plugin_test_runner = PluginTestRunner(self.dummy_plugin_path, {})
        with pytest.raises(Exception):
            plugin_test_runner.validate_plugin()
```

2023-01-30 02:31 UTC, kvfairchild commented on brainscore_core/plugin_management/test_plugins.py
> +RECOGNIZED_TEST_FILES = 'test.*.py'
(Second dot needs escaping to prevent files named `testpy`)

2023-03-30 22:29 UTC, mschrimpf commented
@kvfairchild ping

2023-05-16 14:10 UTC, kvfairchild approved these changes

2023-05-17 00:02 UTC, merged